# Data Transformation Notebook

## Import Libraries

In [76]:
import pandas as pd

## Load Data

In [77]:
df = pd.read_csv('WA_Fn-UseC_-HR-Employee-Attrition.csv')

## Describe Data

In [79]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   object
 2   BusinessTravel            1470 non-null   object
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   object
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   object
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   object
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   object
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   object
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   object
 22  OverTime                  1470 non-null   object
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(26), object(9)
memory usage: 402.1+ KB

## Transform Categorical Values
The following key outlines how the categorical variables were mapped to integer values:
- Attrition: 'Yes': 1, 'No': 0
- BusinessTravel: 'Non-Travel': 0, 'Travel_Rarely': 1, 'Travel_Frequently':2
- Department: 'Sales': 1, 'Research & Development': 2, 'Human Resources':3
- EducationField: 1 for 'Life Sciences': 1, 'Medical': 2, 'Marketing':3, 'Technical Degree': 4, 'Human Resources': 5, 'Other': 6
- Gender: 1 for 'Male': 1, 'Female': 2
- JobRole: 'Sales Executive': 1, 'Research Scientist': 2, 'Laboratory Technician':3, 'Manufacturing Director': 4, 'Healthcare Representative': 5, 'Research Director': 6, 'Human Resources':7, 'Manager':8, 'Sales Representative':9
- MaritalStatus: 'Single': 1, 'Married': 2, 'Divorced': 3
- Over18:'Y': 1, 'N': 0
- OverTime: 'Yes': 1, 'No': 0

In [80]:
df['Attrition'] = df['Attrition'].map({'Yes': 1, 'No': 0})
df['BusinessTravel'] = df['BusinessTravel'].map({'Non-Travel': 0, 'Travel_Rarely': 1, 'Travel_Frequently':2})
df['Department'] = df['Department'].map({'Sales': 1, 'Research & Development': 2, 'Human Resources':3})
df['EducationField'] = df['EducationField'].map({'Life Sciences': 1, 'Medical': 2, 'Marketing':3, 'Technical Degree': 4, 'Human Resources': 5, 'Other': 6})
df['Gender'] = df['Gender'].map({'Male': 1, 'Female': 2})
df['JobRole'] = df['JobRole'].map({'Sales Executive': 1, 'Research Scientist': 2, 'Laboratory Technician':3, 'Manufacturing Director': 4, 'Healthcare Representative': 5, 'Research Director': 6, 'Human Resources':7, 'Manager':8, 'Sales Representative':9})
df['MaritalStatus'] = df['MaritalStatus'].map({'Single': 1, 'Married': 2, 'Divorced': 3})
df['Over18'] = df['Over18'].map({'Y': 1, 'N': 0})
df['OverTime'] = df['OverTime'].map({'Yes': 1, 'No': 0})

df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 1470 entries, 0 to 1469
Data columns (total 35 columns):
 #   Column                    Non-Null Count  Dtype
---  ------                    --------------  -----
 0   Age                       1470 non-null   int64
 1   Attrition                 1470 non-null   int64
 2   BusinessTravel            1470 non-null   int64
 3   DailyRate                 1470 non-null   int64
 4   Department                1470 non-null   int64
 5   DistanceFromHome          1470 non-null   int64
 6   Education                 1470 non-null   int64
 7   EducationField            1470 non-null   int64
 8   EmployeeCount             1470 non-null   int64
 9   EmployeeNumber            1470 non-null   int64
 10  EnvironmentSatisfaction   1470 non-null   int64
 11  Gender                    1470 non-null   int64
 12  HourlyRate                1470 non-null   int64
 13  JobInvolvement            1470 non-null   int64
 14  JobLevel                  1470 non-null   int64
 15  JobRole                   1470 non-null   int64
 16  JobSatisfaction           1470 non-null   int64
 17  MaritalStatus             1470 non-null   int64
 18  MonthlyIncome             1470 non-null   int64
 19  MonthlyRate               1470 non-null   int64
 20  NumCompaniesWorked        1470 non-null   int64
 21  Over18                    1470 non-null   int64
 22  OverTime                  1470 non-null   int64
 23  PercentSalaryHike         1470 non-null   int64
 24  PerformanceRating         1470 non-null   int64
 25  RelationshipSatisfaction  1470 non-null   int64
 26  StandardHours             1470 non-null   int64
 27  StockOptionLevel          1470 non-null   int64
 28  TotalWorkingYears         1470 non-null   int64
 29  TrainingTimesLastYear     1470 non-null   int64
 30  WorkLifeBalance           1470 non-null   int64
 31  YearsAtCompany            1470 non-null   int64
 32  YearsInCurrentRole        1470 non-null   int64
 33  YearsSinceLastPromotion   1470 non-null   int64
 34  YearsWithCurrManager      1470 non-null   int64
dtypes: int64(35)
memory usage: 402.1 KB

## Describe Data

In [81]:
df.describe()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
count,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.0,1470.000000,...,1470.000000,1470.0,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000,1470.000000
mean,36.923810,0.161224,1.086395,802.485714,1.739456,9.192517,2.912925,2.153741,1.0,1024.865306,...,2.712245,80.0,0.793878,11.279592,2.799320,2.761224,7.008163,4.229252,2.187755,4.123129
std,9.135373,0.367863,0.532170,403.509100,0.527792,8.106864,1.024165,1.383865,0.0,602.024335,...,1.081209,0.0,0.852077,7.780782,1.289271,0.706476,6.126525,3.623137,3.222430,3.568136
min,18.000000,0.000000,0.000000,102.000000,1.000000,1.000000,1.000000,1.000000,1.0,1.000000,...,1.000000,80.0,0.000000,0.000000,0.000000,1.000000,0.000000,0.000000,0.000000,0.000000
25%,30.000000,0.000000,1.000000,465.000000,1.000000,2.000000,2.000000,1.000000,1.0,491.250000,...,2.000000,80.0,0.000000,6.000000,2.000000,2.000000,3.000000,2.000000,0.000000,2.000000
50%,36.000000,0.000000,1.000000,802.000000,2.000000,7.000000,3.000000,2.000000,1.0,1020.500000,...,3.000000,80.0,1.000000,10.000000,3.000000,3.000000,5.000000,3.000000,1.000000,3.000000
75%,43.000000,0.000000,1.000000,1157.000000,2.000000,14.000000,4.000000,3.000000,1.0,1555.750000,...,4.000000,80.0,1.000000,15.000000,3.000000,3.000000,9.000000,7.000000,3.000000,7.000000
max,60.000000,1.000000,2.000000,1499.000000,3.000000,29.000000,5.000000,6.000000,1.0,2068.000000,...,4.000000,80.0,3.000000,40.000000,6.000000,4.000000,40.000000,18.000000,15.000000,17.000000

## Finding Outliers
Outliers were identified using the 1.5 IQR rule.

In [82]:
# Find all the outliers in all columns of a dataframe

def id_outliers(df):
    outliers_dict = {}
    
    for column in df.select_dtypes(include=['number']).columns:
        
        # Calculate Q1 and Q3 & interquartile range.
        Q1 = df[column].quantile(0.25)
        Q3 = df[column].quantile(0.75)
        IQR = Q3 - Q1
        
        # Define the outlier boundaries 
        lower_bound = Q1 - 1.5 * IQR
        upper_bound = Q3 + 1.5 * IQR
        
        # Identify outliers
        outliers = df[(df[column] < lower_bound) | (df[column] > upper_bound)]
        
        # Store outliers in dictionary
        outliers_dict[column] = outliers[column]
    
    # Combine all outliers into a single DataFrame
    outliers_df = pd.DataFrame(outliers_dict)

    return outliers_df

outliers = id_outliers(df)
outlier_counts = outliers.count()
print(outlier_counts)

Age                           0
Attrition                   237
BusinessTravel              427
DailyRate                     0
Department                    0
DistanceFromHome              0
Education                     0
EducationField                0
EmployeeCount                 0
EmployeeNumber                0
EnvironmentSatisfaction       0
Gender                        0
HourlyRate                    0
JobInvolvement                0
JobLevel                      0
JobRole                       0
JobSatisfaction               0
MaritalStatus                 0
MonthlyIncome               114
MonthlyRate                   0
NumCompaniesWorked           52
Over18                        0
OverTime                      0
PercentSalaryHike             0
PerformanceRating           226
RelationshipSatisfaction      0
StandardHours                 0
StockOptionLevel             85
TotalWorkingYears            63
TrainingTimesLastYear       238
WorkLifeBalance               0
YearsAtCompany              104
YearsInCurrentRole           21
YearsSinceLastPromotion     107
YearsWithCurrManager         14
dtype: int64

## Correlation Analysis
Correlation matrix was used to show the strength and directon of the linear relationship between attrition and the other pairs of variables in the dataset.

In [83]:
df.corr()

,Age,Attrition,BusinessTravel,DailyRate,Department,DistanceFromHome,Education,EducationField,EmployeeCount,EmployeeNumber,...,RelationshipSatisfaction,StandardHours,StockOptionLevel,TotalWorkingYears,TrainingTimesLastYear,WorkLifeBalance,YearsAtCompany,YearsInCurrentRole,YearsSinceLastPromotion,YearsWithCurrManager
Age,1.000000,-0.159205,-0.011807,0.010661,0.031882,-0.001686,0.208034,-0.035850,NaN,-0.010145,...,0.053535,NaN,0.037510,0.680381,-0.019621,-0.021490,0.311309,0.212901,0.216513,0.202089
Attrition,-0.159205,1.000000,0.127006,-0.056652,-0.063991,0.077924,-0.031373,0.051567,NaN,-0.010577,...,-0.045872,NaN,-0.137145,-0.171063,-0.059478,-0.063939,-0.134392,-0.160545,-0.033019,-0.156199
BusinessTravel,-0.011807,0.127006,1.000000,-0.015539,0.002640,-0.009696,-0.008670,-0.015275,NaN,-0.018538,...,0.008926,NaN,-0.028257,0.007972,0.016357,0.004209,0.005212,-0.005336,0.005222,-0.000229
DailyRate,0.010661,-0.056652,-0.015539,1.000000,-0.007109,-0.004985,-0.016806,-0.018291,NaN,-0.050990,...,0.007846,NaN,0.042143,0.014515,0.002453,-0.037848,-0.034055,0.009932,-0.033229,-0.026363
Department,0.031882,-0.063991,0.002640,-0.007109,1.000000,-0.017225,-0.007996,0.006415,NaN,0.010895,...,0.022414,NaN,0.012193,0.015762,-0.036875,-0.026383,-0.022920,-0.056315,-0.040061,-0.034282
DistanceFromHome,-0.001686,0.077924,-0.009696,-0.004985,-0.017225,1.000000,0.021042,0.005369,NaN,0.032916,...,0.006557,NaN,0.044872,0.004628,-0.036942,-0.026556,0.009508,0.018845,0.010029,0.014406
Education,0.208034,-0.031373,-0.008670,-0.016806,-0.007996,0.021042,1.000000,0.033467,NaN,0.042070,...,-0.009118,NaN,0.018422,0.148280,-0.025100,0.009819,0.069114,0.060236,0.054254,0.069065
EducationField,-0.035850,0.051567,-0.015275,-0.018291,0.006415,0.005369,0.033467,1.000000,NaN,0.016633,...,-0.000440,NaN,-0.020446,-0.027703,-0.005588,0.047322,-0.022710,-0.015588,-0.029528,-0.010316
EmployeeCount,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
EmployeeNumber,-0.010145,-0.010577,-0.018538,-0.050990,0.010895,0.032916,0.042070,0.016633,NaN,1.000000,...,-0.069861,NaN,0.062227,-0.014365,0.023603,0.010309,-0.011240,-0.008416,-0.009019,-0.009197
EnvironmentSatisfaction,0.010146,-0.103369,-0.011310,0.018355,0.019395,-0.016075,-0.027128,0.061149,NaN,0.017621,...,0.007665,NaN,0.003432,-0.002693,-0.019359,0.027627,0.001458,0.018007,0.016194,-0.004999
Gender,0.036311,-0.029453,0.044896,0.011716,-0.041583,0.001851,0.016547,-0.017465,NaN,-0.022556,...,-0.022868,NaN,-0.012716,0.046881,0.038787,0.002753,0.029747,0.041483,0.026985,0.030599
HourlyRate,0.024287,-0.006846,-0.004164,0.023381,0.004144,0.031131,0.016775,-0.045911,NaN,0.035179,...,0.001330,NaN,0.050263,-0.002334,-0.008548,-0.004607,-0.019582,-0.024106,-0.026716,-0.020123
JobInvolvement,0.029820,-0.130016,0.029300,0.046135,0.024586,0.008783,0.042438,-0.014493,NaN,-0.006888,...,0.034297,NaN,0.021523,-0.005533,-0.015338,-0.014617,-0.021355,0.008717,-0.024184,0.025976
JobLevel,0.509604,-0.169105,-0.011696,0.002966,-0.101963,0.005303,0.101589,-0.006867,NaN,-0.018519,...,0.021642,NaN,0.013984,0.782208,-0.018191,0.037818,0.534739,0.389447,0.353885,0.375281
JobRole,0.149806,-0.003153,0.024907,-0.000916,0.248710,-0.044819,-0.038056,0.033945,NaN,0.001045,...,0.012476,NaN,-0.033192,0.263634,0.011754,0.043919,0.137231,0.033762,0.089556,0.022228
JobSatisfaction,-0.004892,-0.103481,0.008666,0.030571,-0.021001,-0.003669,-0.011296,-0.035976,NaN,-0.046247,...,-0.012454,NaN,0.010690,-0.020185,-0.005779,-0.019459,-0.003803,-0.002305,-0.018214,-0.027656
MaritalStatus,0.095029,-0.162070,-0.030915,0.069586,0.056073,0.014437,-0.004053,0.013465,NaN,0.008155,...,-0.022549,NaN,0.662577,0.077886,-0.010629,-0.014708,0.059986,0.065822,0.030915,0.038570
MonthlyIncome,0.497855,-0.159840,-0.013450,0.007707,-0.053130,-0.017014,0.094961,-0.012517,NaN,-0.014829,...,0.025873,NaN,0.005408,0.772893,-0.021736,0.030683,0.514285,0.363818,0.344978,0.344079
MonthlyRate,0.028051,0.015170,-0.008440,-0.032182,-0.023642,0.027473,-0.026084,-0.034400,NaN,0.012648,...,-0.004085,NaN,-0.034323,0.026442,0.001467,0.007963,-0.023655,-0.012815,0.001567,-0.036746
NumCompaniesWorked,0.299635,0.043494,-0.030743,0.038153,0.035882,-0.029251,0.126317,-0.007220,NaN,-0.001251,...,0.052733,NaN,0.030075,0.237639,-0.066054,-0.008366,-0.118421,-0.090754,-0.036814,-0.110319
Over18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
OverTime,0.028062,0.246118,0.042752,0.009135,-0.007481,0.025514,-0.020322,0.018606,NaN,-0.024037,...,0.048493,NaN,-0.000449,0.012754,-0.079113,-0.027092,-0.011687,-0.029758,-0.012239,-0.041586
PercentSalaryHike,0.003634,-0.013478,-0.025727,0.022704,0.007840,0.040235,-0.011111,-0.019401,NaN,-0.012944,...,-0.040490,NaN,0.007528,-0.020608,-0.005221,-0.003280,-0.035991,-0.001520,-0.022154,-0.011985
PerformanceRating,0.001904,0.002889,0.001683,0.000473,0.024604,0.027110,-0.024539,-0.014649,NaN,-0.020359,...,-0.031351,NaN,0.003506,0.006744,-0.015579,0.002572,0.003435,0.034986,0.017896,0.022827
RelationshipSatisfaction,0.053535,-0.045872,0.008926,0.007846,0.022414,0.006557,-0.009118,-0.000440,NaN,-0.069861,...,1.000000,NaN,-0.045952,0.024054,0.002497,0.019604,0.019367,-0.015123,0.033493,-0.000867
StandardHours,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,...,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
StockOptionLevel,0.037510,-0.137145,-0.028257,0.042143,0.012193,0.044872,0.018422,-0.020446,NaN,0.062227,...,-0.045952,NaN,1.000000,0.010136,0.011274,0.004129,0.015058,0.050818,0.014352,0.024698
TotalWorkingYears,0.680381,-0.171063,0.007972,0.014515,0.015762,0.004628,0.148280,-0.027703,NaN,-0.014365,...,0.024054,NaN,0.010136,1.000000,-0.035662,0.001008,0.628133,0.460365,0.404858,0.459188
TrainingTimesLastYear,-0.019621,-0.059478,0.016357,0.002453,-0.036875,-0.036942,-0.025100,-0.005588,NaN,0.023603,...,0.002497,NaN,0.011274,-0.035662,1.000000,0.028072,0.003569,-0.005738,-0.002067,-0.004096
WorkLifeBalance,-0.021490,-0.063939,0.004209,-0.037848,-0.026383,-0.026556,0.009819,0.047322,NaN,0.010309,...,0.019604,NaN,0.004129,0.001008,0.028072,1.000000,0.012089,0.049856,0.008941,0.002759
YearsAtCompany,0.311309,-0.134392,0.005212,-0.034055,-0.022920,0.009508,0.069114,-0.022710,NaN,-0.011240,...,0.019367,NaN,0.015058,0.628133,0.003569,0.012089,1.000000,0.758754,0.618409,0.769212
YearsInCurrentRole,0.212901,-0.160545,-0.005336,0.009932,-0.056315,0.018845,0.060236,-0.015588,NaN,-0.008416,...,-0.015123,NaN,0.050818,0.460365,-0.005738,0.049856,0.758754,1.000000,0.548056,0.714365
YearsSinceLastPromotion,0.216513,-0.033019,0.005222,-0.033229,-0.040061,0.010029,0.054254,-0.029528,NaN,-0.009019,...,0.033493,NaN,0.014352,0.404858,-0.002067,0.008941,0.618409,0.548056,1.000000,0.510224
YearsWithCurrManager,0.202089,-0.156199,-0.000229,-0.026363,-0.034282,0.014406,0.069065,-0.010316,NaN,-0.009197,...,-0.000867,NaN,0.024698,0.459188,-0.004096,0.002759,0.769212,0.714365,0.510224,1.000000

## Export Clean Dataframe

In [85]:
df.to_csv('attrition_data_clean')